In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
columns = ["lettr", "x-box", "y-box", "width", "height", "onpix", "x-bar","y-bar", "x2bar", "y2bar", "xybar", "x2ybr", "xy2br", "x-ege", "xegvy","y-ege", "yegvx"]

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/2/A/letter-recognition.data', names=columns)

In [ ]:
df.head(10)

lettr  x-box  y-box  width  height  onpix  x-bar  y-bar  x2bar  y2bar  \
0     T      2      8      3       5      1      8     13      0      6   
1     I      5     12      3       7      2     10      5      5      4   
2     D      4     11      6       8      6     10      6      2      6   
3     N      7     11      6       6      3      5      9      4      6   
4     G      2      1      3       1      1      8      6      6      6   
5     S      4     11      5       8      3      8      8      6      9   
6     B      4      2      5       4      4      8      7      6      6   
7     A      1      1      3       2      1      8      2      2      2   
8     J      2      2      4       4      2     10      6      2      6   
9     M     11     15     13       9      7     13      2      6      2   

   xybar  x2ybr  xy2br  x-ege  xegvy  y-ege  yegvx  
0      6     10      8      0      8      0      8  
1     13      3      9      2      8      4     10  
2     10      3      7      3      7      3      9  
3      4      4     10      6     10      2      8  
4      6      5      9      1      7      5     10  
5      5      6      6      0      8      9      7  
6      7      6      6      2      8      7     10  
7      8      2      8      1      6      2      7  
8     12      4      8      1      6      1      7  
9     12      1      9      8      1      1      8

In [ ]:
x = df.drop("lettr", axis=1).values
y = df["lettr"].values

In [ ]:
x.shape

(20000, 16)

In [ ]:
y.shape

(20000,)

In [ ]:
np.unique(y)

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype=object)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
def shape():
    print("Train Shape :",x_train.shape)
    print("Test Shape :",x_test.shape)
    print("y_train shape :",y_train.shape)
    print("y_test shape :",y_test.shape)

shape()

Train Shape : (16000, 16)
Test Shape : (4000, 16)
y_train shape : (16000,)
y_test shape : (4000,)


In [ ]:
x_train[5]

array([4, 7, 6, 5, 8, 8, 8, 4, 4, 6, 7, 8, 7, 8, 5, 8])

In [ ]:
class_names=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M','N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [ ]:
model=Sequential()
model.add(Dense(512, activation='relu', input_shape=(16,)))
model.add(Dropout(0.2))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(26, activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               8704      
                                                                 
 dropout (Dropout)           (None, 512)               0         
                                                                 
 dense_1 (Dense)             (None, 256)               131328    
                                                                 
 dropout_1 (Dropout)         (None, 256)               0         
                                                                 
 dense_2 (Dense)             (None, 26)                6682      
                                                                 
Total params: 146714 (573.10 KB)
Trainable params: 146714 (573.10 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.fit(x_train, y_train, epochs=50, batch_size=128, verbose=1,validation_data=(x_test, y_test))

Epoch 1/50
125/125 [==============================] - 3s 11ms/step - loss: 1.8397 - accuracy: 0.4638 - val_loss: 0.9757 - val_accuracy: 0.7315
Epoch 2/50
125/125 [==============================] - 1s 7ms/step - loss: 0.9833 - accuracy: 0.7036 - val_loss: 0.6925 - val_accuracy: 0.8060
Epoch 3/50
125/125 [==============================] - 1s 8ms/step - loss: 0.7756 - accuracy: 0.7606 - val_loss: 0.5547 - val_accuracy: 0.8403
Epoch 4/50
125/125 [==============================] - 1s 7ms/step - loss: 0.6348 - accuracy: 0.8057 - val_loss: 0.4659 - val_accuracy: 0.8558
Epoch 5/50
125/125 [==============================] - 1s 9ms/step - loss: 0.5645 - accuracy: 0.8213 - val_loss: 0.4020 - val_accuracy: 0.8867
Epoch 6/50
125/125 [==============================] - 1s 9ms/step - loss: 0.4870 - accuracy: 0.8503 - val_loss: 0.3520 - val_accuracy: 0.8907
Epoch 7/50
125/125 [==============================] - 1s 9ms/step - loss: 0.4277 - accuracy: 0.8668 - val_loss: 0.3323 - val_accuracy: 0.8982
Epoch

In [ ]:
predictions = model.predict(x_test)

125/125 [==============================] - 0s 2ms/step


In [ ]:
predictions[0]

array([1.3697755e-09, 8.2029139e-09, 1.8564629e-08, 4.6494570e-08,
       1.5772352e-07, 1.4796251e-05, 1.3592677e-05, 1.2402659e-12,
       9.9890763e-01, 1.0441396e-03, 7.2896675e-11, 3.4832487e-10,
       5.4484125e-18, 3.2169959e-14, 2.0613394e-08, 4.2586512e-06,
       5.6363056e-06, 2.7002166e-11, 9.6541980e-06, 9.8278319e-09,
       3.2619645e-14, 3.8633031e-11, 7.4385581e-16, 2.0242337e-10,
       1.1732780e-11, 1.4782998e-10], dtype=float32)

In [ ]:
x_test[0]

array([ 4, 11,  3,  6,  2, 10,  5,  4,  4, 12,  3,  7,  3,  8,  5, 10])

In [ ]:
class_names[y_test[0]]

'I'

In [ ]:
predict = model.predict([[2, 2, 3, 3, 2, 8, 7, 3, 8, 6, 6, 8, 2, 8, 5, 9]])
last = np.argmax(predict)
class_names[last]

1/1 [==============================] - 0s 75ms/step


'X'

In [ ]:
index=10
print(predictions[index])
final_value=np.argmax(predictions[index])
print("Actual label :",y_test[index])
print("Predicted label :",final_value)
print("Class (A-Z) :",class_names[final_value])

[6.0481535e-16 1.3087695e-11 3.1916272e-05 3.0824895e-17 5.5109325e-08
 2.8345547e-13 9.9994129e-01 2.4309768e-14 9.5500300e-06 4.6545387e-10
 9.9490415e-15 2.5162694e-06 1.5644670e-25 7.0613911e-22 1.4186610e-10
 4.2823416e-09 2.3050302e-06 1.1719476e-15 1.2306885e-05 3.3035148e-11
 5.4876924e-18 1.0090595e-18 1.0610345e-23 2.1736519e-13 1.4364535e-15
 1.3548840e-10]
Actual label : 6
Predicted label : 6
Class (A-Z) : G
